# Generated by Django 3.2.12 on 2022-06-29 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('team1', models.CharField(max_length=200, verbose_name='First team name')),
                ('team2', models.CharField(max_length=200, verbose_name='Second team name')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league_app.league', verbose_name='Current league')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('9', '10:9'), ('8', '10:8'), ('7', '10:7'), ('6', '10:6'), ('5', '10:5'), ('4', '10:4'), ('3', '10:3'), ('2', '10:2'), ('1', '10:1'), ('0', '10:0')], max_length=1)),
                ('winner', models.CharField(choices=[('1', 'TEAM 1'), ('2', 'TEAM 2')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('atk1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atk1', to=settings.AUTH_USER_MODEL, verbose_name='atk1')),
                ('atk2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atk2', to=settings.AUTH_USER_MODEL, verbose_name='atk2')),
                ('def1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='def1', to=settings.AUTH_USER_MODEL, verbose_name='def1')),
                ('def2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='def2', to=settings.AUTH_USER_MODEL, verbose_name='def2')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league_app.league')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league_app.league')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['league'],
                'unique_together': {('user', 'league')},
            },
        ),
    ]
