# Generated by Django 3.2.12 on 2022-07-01 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='mvp_atk_def',
            field=models.IntegerField(default=1, verbose_name='Min games for Attack and Defense MVP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='mvp_hybrid',
            field=models.IntegerField(default=1, verbose_name='Min games for Hybrid MVP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='mvp_hybrid_abs_tol',
            field=models.IntegerField(default=1, verbose_name='Hybrid MVP absolute tolerance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='mvp_hybrid_rel_tol',
            field=models.FloatField(default=1, verbose_name='Hybrid MVP relative tolerance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='mvp_total',
            field=models.IntegerField(default=1, verbose_name='Min games for Total MVP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
